// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppStatus {
    "name" = "";
    "runtime" = "";
    "frontend" = "";
    "storage" = "";
    "startedAt" = "";
    "importTarget" = "";
    "libraryCount" = 0;

    constructor($$source: Partial<AppStatus> = {}) {
        Object.assign(this, $$source);
    }

    static createFrom($$source: any = {}): AppStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppStatus($$parsedSource as Partial<AppStatus>);
    }
}

export class FlashcardDTO {
    "id" = "";
    "level" = "";
    "category" = "";
    "name" = "";
    "mean" = "";
    "hiragana" = "";
    "image": string | null = null;
    "audio": string | null = null;
    "example": string | null = null;
    "note" = "";
    "bookmarked" = false;

    constructor($$source: Partial<FlashcardDTO> = {}) {
        Object.assign(this, $$source);
    }

    static createFrom($$source: any = {}): FlashcardDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlashcardDTO($$parsedSource as Partial<FlashcardDTO>);
    }
}

export class FlashcardFilter {
    "level" = "";
    "category" = "";
    "search" = "";
    "limit" = 0;
    "offset" = 0;

    constructor($$source: Partial<FlashcardFilter> = {}) {
        Object.assign(this, $$source);
    }

    static createFrom($$source: any = {}): FlashcardFilter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlashcardFilter($$parsedSource as Partial<FlashcardFilter>);
    }
}

export class ImportOptions {
    "replaceLibrary" = false;
    "dryRun" = false;

    constructor($$source: Partial<ImportOptions> = {}) {
        Object.assign(this, $$source);
    }

    static createFrom($$source: any = {}): ImportOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportOptions($$parsedSource as Partial<ImportOptions>);
    }
}

export class ImportResult {
    "batchId" = 0;
    "sourceSha256" = "";
    "totalRows" = 0;
    "validRows" = 0;
    "invalidRows" = 0;
    "inserted" = 0;
    "updated" = 0;
    "errors": ValidationError[] = [];

    constructor($$source: Partial<ImportResult> = {}) {
        Object.assign(this, $$source);
    }

    static createFrom($$source: any = {}): ImportResult {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ($$parsedSource && "errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField7_0($$parsedSource["errors"]);
        }
        return new ImportResult($$parsedSource as Partial<ImportResult>);
    }
}

export class LibrarySummary {
    "total" = 0;
    "shown" = 0;
    "byLevel": { [_ in string]?: number } = {};

    constructor($$source: Partial<LibrarySummary> = {}) {
        Object.assign(this, $$source);
    }

    static createFrom($$source: any = {}): LibrarySummary {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ($$parsedSource && "byLevel" in $$parsedSource) {
            $$parsedSource["byLevel"] = $$createField2_0($$parsedSource["byLevel"]);
        }
        return new LibrarySummary($$parsedSource as Partial<LibrarySummary>);
    }
}

export class NotificationFlashcard {
    "id" = "";
    "level" = "";
    "category" = "";
    "name" = "";
    "mean" = "";
    "hiragana" = "";
    "example": string | null = null;

    constructor($$source: Partial<NotificationFlashcard> = {}) {
        Object.assign(this, $$source);
    }

    static createFrom($$source: any = {}): NotificationFlashcard {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotificationFlashcard($$parsedSource as Partial<NotificationFlashcard>);
    }
}

export class NotificationPayload {
    "id" = "";
    "title" = "";
    "message" = "";
    "card": NotificationFlashcard = new NotificationFlashcard();
    "createdAt" = "";

    constructor($$source: Partial<NotificationPayload> = {}) {
        Object.assign(this, $$source);
    }

    static createFrom($$source: any = {}): NotificationPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ($$parsedSource && "card" in $$parsedSource) {
            $$parsedSource["card"] = NotificationFlashcard.createFrom($$parsedSource["card"]);
        }
        return new NotificationPayload($$parsedSource as Partial<NotificationPayload>);
    }
}

export class StudySettingsDTO {
    "selectedLevels": string[] = [];
    "enabledCategories": string[] = [];
    "orderMode" = "sequential";
    "revealAnswers" = false;
    "dailyGoal" = 10;
    "notificationEnabled" = false;
    "notificationPaused" = true;
    "notificationIntervalMinutes" = 1;
    "lastNotificationStatus" = "";
    "lastNotificationStatusUpdatedAt" = "";

    constructor($$source: Partial<StudySettingsDTO> = {}) {
        Object.assign(this, $$source);
    }

    static createFrom($$source: any = {}): StudySettingsDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StudySettingsDTO($$parsedSource as Partial<StudySettingsDTO>);
    }
}

export class StudyStateDTO {
    "currentCard": FlashcardDTO | null = null;
    "currentIndex" = -1;
    "totalCards" = 0;
    "settings": StudySettingsDTO = new StudySettingsDTO();

    constructor($$source: Partial<StudyStateDTO> = {}) {
        Object.assign(this, $$source);
    }

    static createFrom($$source: any = {}): StudyStateDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ($$parsedSource && $$parsedSource["currentCard"] !== null && $$parsedSource["currentCard"] !== undefined) {
            $$parsedSource["currentCard"] = FlashcardDTO.createFrom($$parsedSource["currentCard"]);
        }
        if ($$parsedSource && "settings" in $$parsedSource) {
            $$parsedSource["settings"] = StudySettingsDTO.createFrom($$parsedSource["settings"]);
        }
        return new StudyStateDTO($$parsedSource as Partial<StudyStateDTO>);
    }
}

export class ValidationError {
    "index"?: number | null;
    "field"?: string;
    "message" = "";

    constructor($$source: Partial<ValidationError> = {}) {
        Object.assign(this, $$source);
    }

    static createFrom($$source: any = {}): ValidationError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValidationError($$parsedSource as Partial<ValidationError>);
    }
}

// Private type creation functions
const $$createType0 = ValidationError.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map((source: any) => String(source), $Create.Any);
