// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Flashcard {
    "ID": string;
    "Level": string;
    "Category": string;
    "Name": string;
    "Mean": string;
    "Hiragana": string;
    "Example": string | null;

    /** Creates a new Flashcard instance. */
    constructor($$source: Partial<Flashcard> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Level" in $$source)) {
            this["Level"] = "";
        }
        if (!("Category" in $$source)) {
            this["Category"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Mean" in $$source)) {
            this["Mean"] = "";
        }
        if (!("Hiragana" in $$source)) {
            this["Hiragana"] = "";
        }
        if (!("Example" in $$source)) {
            this["Example"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Flashcard instance from a string or object.
     */
    static createFrom($$source: any = {}): Flashcard {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Flashcard($$parsedSource as Partial<Flashcard>);
    }
}

export class Payload {
    "id": string;
    "title": string;
    "message": string;
    "card": Flashcard;
    "createdAt": string;

    /** Creates a new Payload instance. */
    constructor($$source: Partial<Payload> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("card" in $$source)) {
            this["card"] = (new Flashcard());
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Payload instance from a string or object.
     */
    static createFrom($$source: any = {}): Payload {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("card" in $$parsedSource) {
            $$parsedSource["card"] = $$createField3_0($$parsedSource["card"]);
        }
        return new Payload($$parsedSource as Partial<Payload>);
    }
}

export class Settings {
    "enabled": boolean;
    "paused": boolean;
    "intervalMinutes": number;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("paused" in $$source)) {
            this["paused"] = false;
        }
        if (!("intervalMinutes" in $$source)) {
            this["intervalMinutes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = Flashcard.createFrom;
